version: '3'

services:
  ssurvey-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    container_name: ssurvey-frontend
    restart: unless-stopped
    # 如果需要自定义环境变量
    # environment:
    #   - VUE_APP_API_URL=https://api.example.com
    # 如果需要连接到后端服务
    # depends_on:
    #   - ssurvey-backend
    # 如果需要挂载卷
    # volumes:
    #   - ./nginx.conf:/etc/nginx/conf.d/default.conf

  # 如果有后端服务，可以在这里配置
  # ssurvey-backend:
  #   image: your-backend-image
  #   ports:
  #     - "8080:8080"
  #   container_name: ssurvey-backend
  #   restart: unless-stopped 